import {MemoryEntity, Prop} from '../decorators';
import {Byte, Float, Int32} from "../decorators/memory/native-types";
import {Injector} from "../injector";
import {kernel} from "../libs";
import {Process} from "../process";
import {Clock} from "./clock";
import {FunctionAddress} from "./functions";
import {GameBase} from "./game-base";
import {Vehicle, Player} from "./ped";
import {Weather} from "./";
